### ISSUE TITLE
Options for better browser support?

### ISSUE THREAD

**Issue by garypaduana** [kittykatattack/tink#1]
Currently Tink is using a lot of features from ES6 but some of these are not supported by most browsers.  Default values, for instance, is only supported by Firefox at the moment.  [It's not supported until Chrome v49](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters), which hasn't been released yet.  Are there any tools similar to Tink that would be recommended until browser support catches up?

**Comment by kittykatattack** [comment]
The source code is written in ES6, but in the `bin` folder you'll find the compiled ES5 code which should work in current browsers.

**Comment by garypaduana** [comment]
Ah, great, thank you for pointing that out.  I didn't notice anything in the readme and went straight to src.
